# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Api.MiniRanking do
  @moduledoc """
  API calls for all endpoints tagged `MiniRanking`.
  """

  alias APIBL.Connection
  import APIBL.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (APIBL.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:rank` (integer()): 
    - `:country` (String.t): 
    - `:countryRank` (integer()): 
    - `:leaderboardContext` (LeaderboardContexts): 
    - `:friends` (boolean()): 

  ### Returns

  - `{:ok, APIBL.Model.MiniRankingResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec mini_ranking_get_mini_rankings(Tesla.Env.client, keyword()) :: {:ok, APIBL.Model.MiniRankingResponse.t} | {:error, Tesla.Env.t}
  def mini_ranking_get_mini_rankings(connection, opts \\ []) do
    optional_params = %{
      :rank => :query,
      :country => :query,
      :countryRank => :query,
      :leaderboardContext => :query,
      :friends => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/minirankings")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, APIBL.Model.MiniRankingResponse}
    ])
  end
end
