# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Api.Modifiers do
  @moduledoc """
  API calls for all endpoints tagged `Modifiers`.
  """

  alias APIBL.Connection
  import APIBL.RequestBuilder

  @doc """
  Retrieve Modifiers
  Provides a list of Beat Saber modifiers and their associated values.

  ### Parameters

  - `connection` (APIBL.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, %{}}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec modifiers_get_modifiers(Tesla.Env.client, keyword()) :: {:ok, map()} | {:error, Tesla.Env.t}
  def modifiers_get_modifiers(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/modifiers")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %{}}
    ])
  end
end
