# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Api.Patreon do
  @moduledoc """
  API calls for all endpoints tagged `Patreon`.
  """

  alias APIBL.Connection
  import APIBL.RequestBuilder

  @doc """
  Refresh Patreon Link
  Refreshes the Patreon link for the current user, updating their Patreon tier and roles based on the latest information.

  ### Parameters

  - `connection` (APIBL.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec patreon_refresh_my_patreon(Tesla.Env.client, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def patreon_refresh_my_patreon(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/refreshmypatreon")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {400, false},
      {401, false}
    ])
  end
end
