# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Api.PlayerRefresh do
  @moduledoc """
  API calls for all endpoints tagged `PlayerRefresh`.
  """

  alias APIBL.Connection
  import APIBL.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (APIBL.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec player_refresh_refresh_leaderboard_players(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def player_refresh_refresh_leaderboard_players(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/players/leaderboard/#{id}/refresh")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (APIBL.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters
    - `:refreshRank` (boolean()): 

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec player_refresh_refresh_player_action(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def player_refresh_refresh_player_action(connection, id, opts \\ []) do
    optional_params = %{
      :refreshRank => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/player/#{id}/refresh")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (APIBL.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec player_refresh_refresh_players(Tesla.Env.client, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def player_refresh_refresh_players(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/players/refresh")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (APIBL.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec player_refresh_refresh_players_stats(Tesla.Env.client, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def player_refresh_refresh_players_stats(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/players/stats/refresh")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (APIBL.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec player_refresh_refresh_ranks(Tesla.Env.client, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def player_refresh_refresh_ranks(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/players/rankrefresh")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (APIBL.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec player_refresh_refresh_steam_players(Tesla.Env.client, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def player_refresh_refresh_steam_players(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/players/steam/refresh")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end
end
