# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Api.Replayed do
  @moduledoc """
  API calls for all endpoints tagged `Replayed`.
  """

  alias APIBL.Connection
  import APIBL.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (APIBL.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:playerId` (String.t): 

  ### Returns

  - `{:ok, APIBL.Model.ReplayedResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec replayed_get_replayed(Tesla.Env.client, keyword()) :: {:ok, APIBL.Model.ReplayedResponse.t} | {:error, Tesla.Env.t}
  def replayed_get_replayed(connection, opts \\ []) do
    optional_params = %{
      :playerId => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/replayed")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, APIBL.Model.ReplayedResponse}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (APIBL.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec replayed_recalculatereplayed(Tesla.Env.client, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def replayed_recalculatereplayed(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/recalculatereplayed")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (APIBL.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec replayed_wefwefwefwfe(Tesla.Env.client, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def replayed_wefwefwefwfe(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/wefwefwefwfe")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (APIBL.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec replayed_wefwfwfwfwfwf(Tesla.Env.client, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def replayed_wefwfwfwfwfwf(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/wefwfwfwfwfwf")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (APIBL.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec replayed_wfwfwfwefwf(Tesla.Env.client, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def replayed_wfwfwfwefwf(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/wfwfwfwefwf")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end
end
