# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Api.Reweight do
  @moduledoc """
  API calls for all endpoints tagged `Reweight`.
  """

  alias APIBL.Connection
  import APIBL.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (APIBL.Connection): Connection to server
  - `hash` (String.t): 
  - `diff` (String.t): 
  - `mode` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec reweight_approve_reweight(Tesla.Env.client, String.t, String.t, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def reweight_approve_reweight(connection, hash, diff, mode, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/reweight/approve/#{hash}/#{diff}/#{mode}")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (APIBL.Connection): Connection to server
  - `hash` (String.t): 
  - `diff` (String.t): 
  - `mode` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec reweight_cancel_reweight(Tesla.Env.client, String.t, String.t, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def reweight_cancel_reweight(connection, hash, diff, mode, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/reweight/cancel/#{hash}/#{diff}/#{mode}")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (APIBL.Connection): Connection to server
  - `hash` (String.t): 
  - `diff` (String.t): 
  - `mode` (String.t): 
  - `opts` (keyword): Optional parameters
    - `:keep` (boolean()): 
    - `:type` (integer()): 
    - `:criteriaCheck` (integer()): 
    - `:criteriaCommentary` (String.t): 
    - `:modifiers` (String.t): 

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec reweight_update_reweight(Tesla.Env.client, String.t, String.t, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def reweight_update_reweight(connection, hash, diff, mode, opts \\ []) do
    optional_params = %{
      :keep => :query,
      :type => :query,
      :criteriaCheck => :query,
      :criteriaCommentary => :query,
      :modifiers => :query
    }

    request =
      %{}
      |> method(:post)
      |> url("/reweight/#{hash}/#{diff}/#{mode}")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end
end
