# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Api.Screenshot do
  @moduledoc """
  API calls for all endpoints tagged `Screenshot`.
  """

  alias APIBL.Connection
  import APIBL.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (APIBL.Connection): Connection to server
  - `width` (integer()): 
  - `height` (integer()): 
  - `context` (String.t): 
  - `imagename` (String.t): 
  - `path` (String.t): 
  - `opts` (keyword): Optional parameters
    - `:queryStringParameters` (%{optional(String.t) => String.t}): 

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec screenshot_get_screenshot(Tesla.Env.client, integer(), integer(), String.t, String.t, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def screenshot_get_screenshot(connection, width, height, context, imagename, path, opts \\ []) do
    optional_params = %{
      :queryStringParameters => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/screenshot/#{width}x#{height}/#{imagename}/#{context}/#{path}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end
end
