# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.AccuracyTracker do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :accRight,
    :accLeft,
    :leftPreswing,
    :rightPreswing,
    :averagePreswing,
    :leftPostswing,
    :rightPostswing,
    :leftTimeDependence,
    :rightTimeDependence,
    :leftAverageCut,
    :rightAverageCut,
    :gridAcc,
    :fcAcc
  ]

  @type t :: %__MODULE__{
    :accRight => float() | nil,
    :accLeft => float() | nil,
    :leftPreswing => float() | nil,
    :rightPreswing => float() | nil,
    :averagePreswing => float() | nil,
    :leftPostswing => float() | nil,
    :rightPostswing => float() | nil,
    :leftTimeDependence => float() | nil,
    :rightTimeDependence => float() | nil,
    :leftAverageCut => [float()] | nil,
    :rightAverageCut => [float()] | nil,
    :gridAcc => [float()] | nil,
    :fcAcc => float() | nil
  }

  def decode(value) do
    value
  end
end

