# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.AchievementLevel do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :image,
    :smallImage,
    :name,
    :description,
    :detailedDescription,
    :color,
    :value,
    :level,
    :achievementDescriptionId
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :image => String.t | nil,
    :smallImage => String.t | nil,
    :name => String.t | nil,
    :description => String.t | nil,
    :detailedDescription => String.t | nil,
    :color => String.t | nil,
    :value => float() | nil,
    :level => integer() | nil,
    :achievementDescriptionId => integer() | nil
  }

  def decode(value) do
    value
  end
end

