# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.Achievement do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :playerId,
    :player,
    :achievementDescriptionId,
    :achievementDescription,
    :level,
    :timeset,
    :count
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :playerId => String.t | nil,
    :player => APIBL.Model.Player.t | nil,
    :achievementDescriptionId => integer() | nil,
    :achievementDescription => APIBL.Model.AchievementDescription.t | nil,
    :level => APIBL.Model.AchievementLevel.t | nil,
    :timeset => integer() | nil,
    :count => integer() | nil
  }

  alias APIBL.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:player, :struct, APIBL.Model.Player)
     |> Deserializer.deserialize(:achievementDescription, :struct, APIBL.Model.AchievementDescription)
     |> Deserializer.deserialize(:level, :struct, APIBL.Model.AchievementLevel)
  end
end

