# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.AchievementDescription do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :name,
    :description,
    :link,
    :achievements,
    :levels
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :name => String.t | nil,
    :description => String.t | nil,
    :link => String.t | nil,
    :achievements => [APIBL.Model.Achievement.t] | nil,
    :levels => [APIBL.Model.AchievementLevel.t] | nil
  }

  alias APIBL.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:achievements, :list, APIBL.Model.Achievement)
     |> Deserializer.deserialize(:levels, :list, APIBL.Model.AchievementLevel)
  end
end

