# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.AveragePosition do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :x,
    :y,
    :z
  ]

  @type t :: %__MODULE__{
    :x => float() | nil,
    :y => float() | nil,
    :z => float() | nil
  }

  def decode(value) do
    value
  end
end

