# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.Ban do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :playerId,
    :bannedBy,
    :banReason,
    :timeset,
    :duration
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :playerId => String.t | nil,
    :bannedBy => String.t | nil,
    :banReason => String.t | nil,
    :timeset => integer() | nil,
    :duration => integer() | nil
  }

  def decode(value) do
    value
  end
end

