# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.BanReturn do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :reason,
    :timeset,
    :duration
  ]

  @type t :: %__MODULE__{
    :reason => String.t | nil,
    :timeset => integer() | nil,
    :duration => integer() | nil
  }

  def decode(value) do
    value
  end
end

