# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.ClanReturn do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :name,
    :color,
    :icon,
    :tag,
    :leaderID,
    :playersCount,
    :pp,
    :averageRank,
    :averageAccuracy,
    :rankedPoolPercentCaptured,
    :capturedLeaderboards,
    :players,
    :pendingInvites
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :name => String.t | nil,
    :color => String.t | nil,
    :icon => String.t | nil,
    :tag => String.t | nil,
    :leaderID => String.t | nil,
    :playersCount => integer() | nil,
    :pp => float() | nil,
    :averageRank => float() | nil,
    :averageAccuracy => float() | nil,
    :rankedPoolPercentCaptured => float() | nil,
    :capturedLeaderboards => [APIBL.Model.Leaderboard.t] | nil,
    :players => [String.t] | nil,
    :pendingInvites => [String.t] | nil
  }

  alias APIBL.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:capturedLeaderboards, :list, APIBL.Model.Leaderboard)
  end
end

