# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.Clan do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :name,
    :color,
    :icon,
    :tag,
    :leaderID,
    :description,
    :bio,
    :playersCount,
    :pp,
    :averageRank,
    :averageAccuracy,
    :captureLeaderboardsCount,
    :rankedPoolPercentCaptured,
    :capturedLeaderboards,
    :players,
    :requests,
    :banned
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :name => String.t | nil,
    :color => String.t | nil,
    :icon => String.t | nil,
    :tag => String.t | nil,
    :leaderID => String.t | nil,
    :description => String.t | nil,
    :bio => String.t | nil,
    :playersCount => integer() | nil,
    :pp => float() | nil,
    :averageRank => float() | nil,
    :averageAccuracy => float() | nil,
    :captureLeaderboardsCount => integer() | nil,
    :rankedPoolPercentCaptured => float() | nil,
    :capturedLeaderboards => [APIBL.Model.Leaderboard.t] | nil,
    :players => [APIBL.Model.Player.t] | nil,
    :requests => [APIBL.Model.User.t] | nil,
    :banned => [APIBL.Model.User.t] | nil
  }

  alias APIBL.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:capturedLeaderboards, :list, APIBL.Model.Leaderboard)
     |> Deserializer.deserialize(:players, :list, APIBL.Model.Player)
     |> Deserializer.deserialize(:requests, :list, APIBL.Model.User)
     |> Deserializer.deserialize(:banned, :list, APIBL.Model.User)
  end
end

