# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.CompactScoreResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :score,
    :leaderboard
  ]

  @type t :: %__MODULE__{
    :score => APIBL.Model.CompactScore.t | nil,
    :leaderboard => APIBL.Model.CompactLeaderboard.t | nil
  }

  alias APIBL.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:score, :struct, APIBL.Model.CompactScore)
     |> Deserializer.deserialize(:leaderboard, :struct, APIBL.Model.CompactLeaderboard)
  end
end

