# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.CustomData do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :syncURL,
    :owner,
    :id,
    :hash,
    :shared
  ]

  @type t :: %__MODULE__{
    :syncURL => String.t | nil,
    :owner => String.t | nil,
    :id => String.t | nil,
    :hash => String.t | nil,
    :shared => boolean() | nil
  }

  def decode(value) do
    value
  end
end

