# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.DifficultyResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :value,
    :mode,
    :difficultyName,
    :modeName,
    :status,
    :modifierValues,
    :modifiersRating,
    :nominatedTime,
    :qualifiedTime,
    :rankedTime,
    :stars,
    :predictedAcc,
    :passRating,
    :accRating,
    :techRating,
    :type,
    :njs,
    :nps,
    :notes,
    :bombs,
    :walls,
    :maxScore,
    :duration,
    :requirements
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :value => integer() | nil,
    :mode => integer() | nil,
    :difficultyName => String.t | nil,
    :modeName => String.t | nil,
    :status => APIBL.Model.DifficultyStatus.t | nil,
    :modifierValues => APIBL.Model.ModifiersMap.t | nil,
    :modifiersRating => APIBL.Model.ModifiersRating.t | nil,
    :nominatedTime => integer() | nil,
    :qualifiedTime => integer() | nil,
    :rankedTime => integer() | nil,
    :stars => float() | nil,
    :predictedAcc => float() | nil,
    :passRating => float() | nil,
    :accRating => float() | nil,
    :techRating => float() | nil,
    :type => integer() | nil,
    :njs => float() | nil,
    :nps => float() | nil,
    :notes => integer() | nil,
    :bombs => integer() | nil,
    :walls => integer() | nil,
    :maxScore => integer() | nil,
    :duration => float() | nil,
    :requirements => APIBL.Model.Requirements.t | nil
  }

  alias APIBL.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:status, :struct, APIBL.Model.DifficultyStatus)
     |> Deserializer.deserialize(:modifierValues, :struct, APIBL.Model.ModifiersMap)
     |> Deserializer.deserialize(:modifiersRating, :struct, APIBL.Model.ModifiersRating)
     |> Deserializer.deserialize(:requirements, :struct, APIBL.Model.Requirements)
  end
end

