# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.EventResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :name,
    :endDate,
    :playlistId,
    :image,
    :playerCount,
    :leader
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :name => String.t | nil,
    :endDate => integer() | nil,
    :playlistId => integer() | nil,
    :image => String.t | nil,
    :playerCount => integer() | nil,
    :leader => APIBL.Model.PlayerResponse.t | nil
  }

  alias APIBL.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:leader, :struct, APIBL.Model.PlayerResponse)
  end
end

