# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.EventRanking do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :name,
    :endDate,
    :playlistId,
    :image,
    :leaderboards,
    :players
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :name => String.t | nil,
    :endDate => integer() | nil,
    :playlistId => integer() | nil,
    :image => String.t | nil,
    :leaderboards => [APIBL.Model.Leaderboard.t] | nil,
    :players => [APIBL.Model.EventPlayer.t] | nil
  }

  alias APIBL.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:leaderboards, :list, APIBL.Model.Leaderboard)
     |> Deserializer.deserialize(:players, :list, APIBL.Model.EventPlayer)
  end
end

