# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.EventPlayer do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :eventId,
    :name,
    :playerId,
    :country,
    :rank,
    :countryRank,
    :pp
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :eventId => integer() | nil,
    :name => String.t | nil,
    :playerId => String.t | nil,
    :country => String.t | nil,
    :rank => integer() | nil,
    :countryRank => integer() | nil,
    :pp => float() | nil
  }

  def decode(value) do
    value
  end
end

