# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.ExternalStatus do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :status,
    :timeset,
    :link,
    :responsible
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :status => APIBL.Model.SongStatus.t | nil,
    :timeset => integer() | nil,
    :link => String.t | nil,
    :responsible => String.t | nil
  }

  alias APIBL.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:status, :struct, APIBL.Model.SongStatus)
  end
end

