# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.FailedScore do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :baseScore,
    :modifiedScore,
    :accuracy,
    :playerId,
    :pp,
    :weight,
    :rank,
    :countryRank,
    :replay,
    :modifiers,
    :badCuts,
    :missedNotes,
    :bombCuts,
    :wallsHit,
    :pauses,
    :fullCombo,
    :hmd,
    :timeset,
    :player,
    :leaderboard,
    :error,
    :falsePositive
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :baseScore => integer() | nil,
    :modifiedScore => integer() | nil,
    :accuracy => float() | nil,
    :playerId => String.t | nil,
    :pp => float() | nil,
    :weight => float() | nil,
    :rank => integer() | nil,
    :countryRank => integer() | nil,
    :replay => String.t | nil,
    :modifiers => String.t | nil,
    :badCuts => integer() | nil,
    :missedNotes => integer() | nil,
    :bombCuts => integer() | nil,
    :wallsHit => integer() | nil,
    :pauses => integer() | nil,
    :fullCombo => boolean() | nil,
    :hmd => APIBL.Model.Hmd.t | nil,
    :timeset => String.t | nil,
    :player => APIBL.Model.Player.t | nil,
    :leaderboard => APIBL.Model.Leaderboard.t | nil,
    :error => String.t | nil,
    :falsePositive => boolean() | nil
  }

  alias APIBL.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:hmd, :struct, APIBL.Model.Hmd)
     |> Deserializer.deserialize(:player, :struct, APIBL.Model.Player)
     |> Deserializer.deserialize(:leaderboard, :struct, APIBL.Model.Leaderboard)
  end
end

