# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.FriendActivity do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :player,
    :type,
    :activityObject
  ]

  @type t :: %__MODULE__{
    :player => APIBL.Model.PlayerResponse.t | nil,
    :type => APIBL.Model.FriendActivityType.t | nil,
    :activityObject => any() | nil
  }

  alias APIBL.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:player, :struct, APIBL.Model.PlayerResponse)
     |> Deserializer.deserialize(:type, :struct, APIBL.Model.FriendActivityType)
  end
end

