# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.GraphResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :leaderboardId,
    :diff,
    :mode,
    :modifiers,
    :songName,
    :hash,
    :mapper,
    :acc,
    :timeset,
    :stars,
    :modifiersRating,
    :modifierValues,
    :passRating,
    :accRating,
    :techRating
  ]

  @type t :: %__MODULE__{
    :leaderboardId => String.t | nil,
    :diff => String.t | nil,
    :mode => String.t | nil,
    :modifiers => String.t | nil,
    :songName => String.t | nil,
    :hash => String.t | nil,
    :mapper => String.t | nil,
    :acc => float() | nil,
    :timeset => String.t | nil,
    :stars => float() | nil,
    :modifiersRating => APIBL.Model.ModifiersRating.t | nil,
    :modifierValues => APIBL.Model.ModifiersMap.t | nil,
    :passRating => float() | nil,
    :accRating => float() | nil,
    :techRating => float() | nil
  }

  alias APIBL.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:modifiersRating, :struct, APIBL.Model.ModifiersRating)
     |> Deserializer.deserialize(:modifierValues, :struct, APIBL.Model.ModifiersMap)
  end
end

