# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.HitTracker do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :maxCombo,
    :maxStreak,
    :leftTiming,
    :rightTiming,
    :leftMiss,
    :rightMiss,
    :leftBadCuts,
    :rightBadCuts,
    :leftBombs,
    :rightBombs
  ]

  @type t :: %__MODULE__{
    :maxCombo => integer() | nil,
    :maxStreak => integer() | nil,
    :leftTiming => float() | nil,
    :rightTiming => float() | nil,
    :leftMiss => integer() | nil,
    :rightMiss => integer() | nil,
    :leftBadCuts => integer() | nil,
    :rightBadCuts => integer() | nil,
    :leftBombs => integer() | nil,
    :rightBombs => integer() | nil
  }

  def decode(value) do
    value
  end
end

