# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.Leaderboard do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :songId,
    :song,
    :difficulty,
    :scores,
    :contextExtensions,
    :qualification,
    :reweight,
    :timestamp,
    :leaderboardGroup,
    :changes,
    :playerStats,
    :events,
    :plays,
    :playCount,
    :positiveVotes,
    :starVotes,
    :negativeVotes,
    :voteStars,
    :clanId,
    :clan,
    :clanRanking,
    :clanRankingContested
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :songId => String.t | nil,
    :song => APIBL.Model.Song.t | nil,
    :difficulty => APIBL.Model.DifficultyDescription.t | nil,
    :scores => [APIBL.Model.Score.t] | nil,
    :contextExtensions => [APIBL.Model.ScoreContextExtension.t] | nil,
    :qualification => APIBL.Model.RankQualification.t | nil,
    :reweight => APIBL.Model.RankUpdate.t | nil,
    :timestamp => integer() | nil,
    :leaderboardGroup => APIBL.Model.LeaderboardGroup.t | nil,
    :changes => [APIBL.Model.LeaderboardChange.t] | nil,
    :playerStats => [APIBL.Model.PlayerLeaderboardStats.t] | nil,
    :events => [APIBL.Model.EventRanking.t] | nil,
    :plays => integer() | nil,
    :playCount => integer() | nil,
    :positiveVotes => integer() | nil,
    :starVotes => integer() | nil,
    :negativeVotes => integer() | nil,
    :voteStars => float() | nil,
    :clanId => integer() | nil,
    :clan => APIBL.Model.Clan.t | nil,
    :clanRanking => [APIBL.Model.ClanRanking.t] | nil,
    :clanRankingContested => boolean() | nil
  }

  alias APIBL.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:song, :struct, APIBL.Model.Song)
     |> Deserializer.deserialize(:difficulty, :struct, APIBL.Model.DifficultyDescription)
     |> Deserializer.deserialize(:scores, :list, APIBL.Model.Score)
     |> Deserializer.deserialize(:contextExtensions, :list, APIBL.Model.ScoreContextExtension)
     |> Deserializer.deserialize(:qualification, :struct, APIBL.Model.RankQualification)
     |> Deserializer.deserialize(:reweight, :struct, APIBL.Model.RankUpdate)
     |> Deserializer.deserialize(:leaderboardGroup, :struct, APIBL.Model.LeaderboardGroup)
     |> Deserializer.deserialize(:changes, :list, APIBL.Model.LeaderboardChange)
     |> Deserializer.deserialize(:playerStats, :list, APIBL.Model.PlayerLeaderboardStats)
     |> Deserializer.deserialize(:events, :list, APIBL.Model.EventRanking)
     |> Deserializer.deserialize(:clan, :struct, APIBL.Model.Clan)
     |> Deserializer.deserialize(:clanRanking, :list, APIBL.Model.ClanRanking)
  end
end

