# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.LeaderboardGroupEntry do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :status,
    :timestamp
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :status => APIBL.Model.DifficultyStatus.t | nil,
    :timestamp => integer() | nil
  }

  alias APIBL.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:status, :struct, APIBL.Model.DifficultyStatus)
  end
end

