# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.LeaderboardsInfoResponseWithScore do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :difficulty,
    :qualification,
    :reweight,
    :clanRankingContested,
    :clan,
    :myScore
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :difficulty => APIBL.Model.DifficultyResponse.t | nil,
    :qualification => APIBL.Model.RankQualification.t | nil,
    :reweight => APIBL.Model.RankUpdate.t | nil,
    :clanRankingContested => boolean() | nil,
    :clan => APIBL.Model.Clan.t | nil,
    :myScore => APIBL.Model.ScoreResponseWithAcc.t | nil
  }

  alias APIBL.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:difficulty, :struct, APIBL.Model.DifficultyResponse)
     |> Deserializer.deserialize(:qualification, :struct, APIBL.Model.RankQualification)
     |> Deserializer.deserialize(:reweight, :struct, APIBL.Model.RankUpdate)
     |> Deserializer.deserialize(:clan, :struct, APIBL.Model.Clan)
     |> Deserializer.deserialize(:myScore, :struct, APIBL.Model.ScoreResponseWithAcc)
  end
end

