# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.LeaderboardGroup do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :leaderboards
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :leaderboards => [APIBL.Model.Leaderboard.t] | nil
  }

  alias APIBL.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:leaderboards, :list, APIBL.Model.Leaderboard)
  end
end

