# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.LeaderboardInfoResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :song,
    :difficulty,
    :plays,
    :positiveVotes,
    :starVotes,
    :negativeVotes,
    :voteStars,
    :clan,
    :clanRankingContested,
    :myScore,
    :qualification,
    :reweight
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :song => APIBL.Model.Song.t | nil,
    :difficulty => APIBL.Model.DifficultyResponse.t | nil,
    :plays => integer() | nil,
    :positiveVotes => integer() | nil,
    :starVotes => integer() | nil,
    :negativeVotes => integer() | nil,
    :voteStars => float() | nil,
    :clan => APIBL.Model.Clan.t | nil,
    :clanRankingContested => boolean() | nil,
    :myScore => APIBL.Model.ScoreResponseWithAcc.t | nil,
    :qualification => APIBL.Model.RankQualification.t | nil,
    :reweight => APIBL.Model.RankUpdate.t | nil
  }

  alias APIBL.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:song, :struct, APIBL.Model.Song)
     |> Deserializer.deserialize(:difficulty, :struct, APIBL.Model.DifficultyResponse)
     |> Deserializer.deserialize(:clan, :struct, APIBL.Model.Clan)
     |> Deserializer.deserialize(:myScore, :struct, APIBL.Model.ScoreResponseWithAcc)
     |> Deserializer.deserialize(:qualification, :struct, APIBL.Model.RankQualification)
     |> Deserializer.deserialize(:reweight, :struct, APIBL.Model.RankUpdate)
  end
end

