# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.MapObstacle do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :_time,
    :_lineIndex,
    :_type,
    :_duration,
    :_width,
    :realTime
  ]

  @type t :: %__MODULE__{
    :_time => float() | nil,
    :_lineIndex => integer() | nil,
    :_type => APIBL.Model.ObstacleType.t | nil,
    :_duration => float() | nil,
    :_width => integer() | nil,
    :realTime => float() | nil
  }

  alias APIBL.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:_type, :struct, APIBL.Model.ObstacleType)
  end
end

