# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.MapNote do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :_time,
    :_lineIndex,
    :_lineLayer,
    :_type,
    :_cutDirection,
    :realTime
  ]

  @type t :: %__MODULE__{
    :_time => float() | nil,
    :_lineIndex => integer() | nil,
    :_lineLayer => integer() | nil,
    :_type => APIBL.Model.NoteType.t | nil,
    :_cutDirection => APIBL.Model.NoteCutDirection.t | nil,
    :realTime => float() | nil
  }

  alias APIBL.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:_type, :struct, APIBL.Model.NoteType)
     |> Deserializer.deserialize(:_cutDirection, :struct, APIBL.Model.NoteCutDirection)
  end
end

