# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.MapperTops do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :top1Count,
    :top1Percentage,
    :top3Count,
    :top3Percentage,
    :top5Count,
    :top5Percentage
  ]

  @type t :: %__MODULE__{
    :top1Count => integer() | nil,
    :top1Percentage => float() | nil,
    :top3Count => integer() | nil,
    :top3Percentage => float() | nil,
    :top5Count => integer() | nil,
    :top5Percentage => float() | nil
  }

  def decode(value) do
    value
  end
end

