# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.Metadata do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :itemsPerPage,
    :page,
    :total
  ]

  @type t :: %__MODULE__{
    :itemsPerPage => integer() | nil,
    :page => integer() | nil,
    :total => integer() | nil
  }

  def decode(value) do
    value
  end
end

