# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.MiniRankingResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :global,
    :country,
    :friends
  ]

  @type t :: %__MODULE__{
    :global => [APIBL.Model.MiniRankingPlayer.t] | nil,
    :country => [APIBL.Model.MiniRankingPlayer.t] | nil,
    :friends => [APIBL.Model.MiniRankingPlayer.t] | nil
  }

  alias APIBL.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:global, :list, APIBL.Model.MiniRankingPlayer)
     |> Deserializer.deserialize(:country, :list, APIBL.Model.MiniRankingPlayer)
     |> Deserializer.deserialize(:friends, :list, APIBL.Model.MiniRankingPlayer)
  end
end

