# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.ModifiersMap do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :modifierId,
    :da,
    :fs,
    :sf,
    :ss,
    :gn,
    :na,
    :nb,
    :nf,
    :no,
    :pm,
    :sc,
    :sa,
    :op
  ]

  @type t :: %__MODULE__{
    :modifierId => integer() | nil,
    :da => float() | nil,
    :fs => float() | nil,
    :sf => float() | nil,
    :ss => float() | nil,
    :gn => float() | nil,
    :na => float() | nil,
    :nb => float() | nil,
    :nf => float() | nil,
    :no => float() | nil,
    :pm => float() | nil,
    :sc => float() | nil,
    :sa => float() | nil,
    :op => float() | nil
  }

  def decode(value) do
    value
  end
end

