# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.ModifiersRating do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :fsPredictedAcc,
    :fsPassRating,
    :fsAccRating,
    :fsTechRating,
    :fsStars,
    :ssPredictedAcc,
    :ssPassRating,
    :ssAccRating,
    :ssTechRating,
    :ssStars,
    :sfPredictedAcc,
    :sfPassRating,
    :sfAccRating,
    :sfTechRating,
    :sfStars
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :fsPredictedAcc => float() | nil,
    :fsPassRating => float() | nil,
    :fsAccRating => float() | nil,
    :fsTechRating => float() | nil,
    :fsStars => float() | nil,
    :ssPredictedAcc => float() | nil,
    :ssPassRating => float() | nil,
    :ssAccRating => float() | nil,
    :ssTechRating => float() | nil,
    :ssStars => float() | nil,
    :sfPredictedAcc => float() | nil,
    :sfPassRating => float() | nil,
    :sfAccRating => float() | nil,
    :sfTechRating => float() | nil,
    :sfStars => float() | nil
  }

  def decode(value) do
    value
  end
end

