# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.OAuthApp do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :clientId,
    :name,
    :coverImageUrl,
    :clientSecret,
    :scopes,
    :redirectUrls
  ]

  @type t :: %__MODULE__{
    :clientId => String.t | nil,
    :name => String.t | nil,
    :coverImageUrl => String.t | nil,
    :clientSecret => String.t | nil,
    :scopes => [String.t] | nil,
    :redirectUrls => [String.t] | nil
  }

  def decode(value) do
    value
  end
end

