# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.OculusUser do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :id,
    :avatar,
    :migrated,
    :migratedId
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :id => String.t | nil,
    :avatar => String.t | nil,
    :migrated => boolean() | nil,
    :migratedId => String.t | nil
  }

  def decode(value) do
    value
  end
end

