# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.PatreonFeatures do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :bio,
    :message,
    :leftSaberColor,
    :rightSaberColor
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :bio => String.t | nil,
    :message => String.t | nil,
    :leftSaberColor => String.t | nil,
    :rightSaberColor => String.t | nil
  }

  def decode(value) do
    value
  end
end

