# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.PlayerFriends do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :friends
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :friends => [APIBL.Model.Player.t] | nil
  }

  alias APIBL.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:friends, :list, APIBL.Model.Player)
  end
end

