# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.PlayerSocial do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :service,
    :link,
    :user,
    :userId,
    :playerId
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :service => String.t | nil,
    :link => String.t | nil,
    :user => String.t | nil,
    :userId => String.t | nil,
    :playerId => String.t | nil
  }

  def decode(value) do
    value
  end
end

