# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.PlayerChange do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :timestamp,
    :playerId,
    :oldName,
    :newName,
    :oldCountry,
    :newCountry,
    :changer
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :timestamp => integer() | nil,
    :playerId => String.t | nil,
    :oldName => String.t | nil,
    :newName => String.t | nil,
    :oldCountry => String.t | nil,
    :newCountry => String.t | nil,
    :changer => String.t | nil
  }

  def decode(value) do
    value
  end
end

