# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.QualificationChange do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :timeset,
    :playerId,
    :oldRankability,
    :oldStars,
    :oldAccRating,
    :oldPassRating,
    :oldTechRating,
    :oldType,
    :oldCriteriaMet,
    :oldCriteriaCommentary,
    :oldModifiers,
    :newRankability,
    :newStars,
    :newAccRating,
    :newPassRating,
    :newTechRating,
    :newType,
    :newCriteriaMet,
    :newCriteriaCommentary,
    :newModifiers
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :timeset => integer() | nil,
    :playerId => String.t | nil,
    :oldRankability => float() | nil,
    :oldStars => float() | nil,
    :oldAccRating => float() | nil,
    :oldPassRating => float() | nil,
    :oldTechRating => float() | nil,
    :oldType => integer() | nil,
    :oldCriteriaMet => integer() | nil,
    :oldCriteriaCommentary => String.t | nil,
    :oldModifiers => APIBL.Model.ModifiersMap.t | nil,
    :newRankability => float() | nil,
    :newStars => float() | nil,
    :newAccRating => float() | nil,
    :newPassRating => float() | nil,
    :newTechRating => float() | nil,
    :newType => integer() | nil,
    :newCriteriaMet => integer() | nil,
    :newCriteriaCommentary => String.t | nil,
    :newModifiers => APIBL.Model.ModifiersMap.t | nil
  }

  alias APIBL.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:oldModifiers, :struct, APIBL.Model.ModifiersMap)
     |> Deserializer.deserialize(:newModifiers, :struct, APIBL.Model.ModifiersMap)
  end
end

