# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.RankQualification do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :timeset,
    :rtMember,
    :criteriaTimeset,
    :criteriaMet,
    :criteriaChecker,
    :criteriaCommentary,
    :mapperAllowed,
    :mapperId,
    :mapperQualification,
    :approvalTimeset,
    :approved,
    :approvers,
    :criteriaCheck,
    :modifiers,
    :modifiersRating,
    :changes,
    :comments,
    :criteriaComments,
    :qualityVote,
    :votes,
    :discordChannelId,
    :discordRTChannelId
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :timeset => integer() | nil,
    :rtMember => String.t | nil,
    :criteriaTimeset => integer() | nil,
    :criteriaMet => integer() | nil,
    :criteriaChecker => String.t | nil,
    :criteriaCommentary => String.t | nil,
    :mapperAllowed => boolean() | nil,
    :mapperId => String.t | nil,
    :mapperQualification => boolean() | nil,
    :approvalTimeset => integer() | nil,
    :approved => boolean() | nil,
    :approvers => String.t | nil,
    :criteriaCheck => String.t | nil,
    :modifiers => APIBL.Model.ModifiersMap.t | nil,
    :modifiersRating => APIBL.Model.ModifiersRating.t | nil,
    :changes => [APIBL.Model.QualificationChange.t] | nil,
    :comments => [APIBL.Model.QualificationCommentary.t] | nil,
    :criteriaComments => [APIBL.Model.CriteriaCommentary.t] | nil,
    :qualityVote => integer() | nil,
    :votes => [APIBL.Model.QualificationVote.t] | nil,
    :discordChannelId => String.t | nil,
    :discordRTChannelId => String.t | nil
  }

  alias APIBL.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:modifiers, :struct, APIBL.Model.ModifiersMap)
     |> Deserializer.deserialize(:modifiersRating, :struct, APIBL.Model.ModifiersRating)
     |> Deserializer.deserialize(:changes, :list, APIBL.Model.QualificationChange)
     |> Deserializer.deserialize(:comments, :list, APIBL.Model.QualificationCommentary)
     |> Deserializer.deserialize(:criteriaComments, :list, APIBL.Model.CriteriaCommentary)
     |> Deserializer.deserialize(:votes, :list, APIBL.Model.QualificationVote)
  end
end

