# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.RankVoting do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :scoreId,
    :playerId,
    :hash,
    :diff,
    :mode,
    :rankability,
    :stars,
    :type,
    :timeset,
    :feedbacks
  ]

  @type t :: %__MODULE__{
    :scoreId => integer() | nil,
    :playerId => String.t | nil,
    :hash => String.t | nil,
    :diff => String.t | nil,
    :mode => String.t | nil,
    :rankability => float() | nil,
    :stars => float() | nil,
    :type => integer() | nil,
    :timeset => integer() | nil,
    :feedbacks => [APIBL.Model.VoterFeedback.t] | nil
  }

  alias APIBL.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:feedbacks, :list, APIBL.Model.VoterFeedback)
  end
end

