# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.ReeSabersReaction do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :authorId,
    :author,
    :timeset,
    :reaction
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :authorId => String.t | nil,
    :author => APIBL.Model.Player.t | nil,
    :timeset => integer() | nil,
    :reaction => APIBL.Model.ReeSaberReaction.t | nil
  }

  alias APIBL.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:author, :struct, APIBL.Model.Player)
     |> Deserializer.deserialize(:reaction, :struct, APIBL.Model.ReeSaberReaction)
  end
end

