# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.ReeSabersComment do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :playerId,
    :player,
    :timeset,
    :edited,
    :editTimeset,
    :value,
    :reactions
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :playerId => String.t | nil,
    :player => APIBL.Model.Player.t | nil,
    :timeset => integer() | nil,
    :edited => boolean() | nil,
    :editTimeset => integer() | nil,
    :value => String.t | nil,
    :reactions => [APIBL.Model.ReeSabersReaction.t] | nil
  }

  alias APIBL.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:player, :struct, APIBL.Model.Player)
     |> Deserializer.deserialize(:reactions, :list, APIBL.Model.ReeSabersReaction)
  end
end

