# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.ReplayedResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :player,
    :mapper
  ]

  @type t :: %__MODULE__{
    :player => APIBL.Model.ReplayedPlayerResponse.t | nil,
    :mapper => APIBL.Model.ReplayedMapperResponse.t | nil
  }

  alias APIBL.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:player, :struct, APIBL.Model.ReplayedPlayerResponse)
     |> Deserializer.deserialize(:mapper, :struct, APIBL.Model.ReplayedMapperResponse)
  end
end

