# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.ReplayOffsets do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :frames,
    :notes,
    :walls,
    :heights,
    :pauses
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :frames => integer() | nil,
    :notes => integer() | nil,
    :walls => integer() | nil,
    :heights => integer() | nil,
    :pauses => integer() | nil
  }

  def decode(value) do
    value
  end
end

