# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.ReplayedPlayerResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :topMappers,
    :topMappersPercentage,
    :topMaps,
    :topFailed,
    :topRestarted,
    :eventsParticipation,
    :minutesPlayed,
    :topCategory,
    :misses,
    :hits,
    :restarts,
    :fails,
    :plays,
    :activeDays,
    :daysStreak
  ]

  @type t :: %__MODULE__{
    :topMappers => [APIBL.Model.TopMapper.t] | nil,
    :topMappersPercentage => [APIBL.Model.TopMapper.t] | nil,
    :topMaps => [APIBL.Model.TopMapTime.t] | nil,
    :topFailed => [APIBL.Model.TopMapCount.t] | nil,
    :topRestarted => [APIBL.Model.TopMapCount.t] | nil,
    :eventsParticipation => APIBL.Model.EventsParticipation.t | nil,
    :minutesPlayed => float() | nil,
    :topCategory => String.t | nil,
    :misses => integer() | nil,
    :hits => integer() | nil,
    :restarts => integer() | nil,
    :fails => integer() | nil,
    :plays => integer() | nil,
    :activeDays => integer() | nil,
    :daysStreak => integer() | nil
  }

  alias APIBL.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:topMappers, :list, APIBL.Model.TopMapper)
     |> Deserializer.deserialize(:topMappersPercentage, :list, APIBL.Model.TopMapper)
     |> Deserializer.deserialize(:topMaps, :list, APIBL.Model.TopMapTime)
     |> Deserializer.deserialize(:topFailed, :list, APIBL.Model.TopMapCount)
     |> Deserializer.deserialize(:topRestarted, :list, APIBL.Model.TopMapCount)
     |> Deserializer.deserialize(:eventsParticipation, :struct, APIBL.Model.EventsParticipation)
  end
end

