# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.SaverScoreResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :baseScore,
    :modifiedScore,
    :accuracy,
    :pp,
    :rank,
    :modifiers,
    :leaderboardId,
    :timeset,
    :timepost,
    :player
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :baseScore => integer() | nil,
    :modifiedScore => integer() | nil,
    :accuracy => float() | nil,
    :pp => float() | nil,
    :rank => integer() | nil,
    :modifiers => String.t | nil,
    :leaderboardId => String.t | nil,
    :timeset => String.t | nil,
    :timepost => integer() | nil,
    :player => String.t | nil
  }

  def decode(value) do
    value
  end
end

