# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.ScoreGraphTracker do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :graph
  ]

  @type t :: %__MODULE__{
    :graph => [float()] | nil
  }

  def decode(value) do
    value
  end
end

