# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.ScoreStatistic do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :hitTracker,
    :accuracyTracker,
    :winTracker,
    :scoreGraphTracker
  ]

  @type t :: %__MODULE__{
    :hitTracker => APIBL.Model.HitTracker.t | nil,
    :accuracyTracker => APIBL.Model.AccuracyTracker.t | nil,
    :winTracker => APIBL.Model.WinTracker.t | nil,
    :scoreGraphTracker => APIBL.Model.ScoreGraphTracker.t | nil
  }

  alias APIBL.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:hitTracker, :struct, APIBL.Model.HitTracker)
     |> Deserializer.deserialize(:accuracyTracker, :struct, APIBL.Model.AccuracyTracker)
     |> Deserializer.deserialize(:winTracker, :struct, APIBL.Model.WinTracker)
     |> Deserializer.deserialize(:scoreGraphTracker, :struct, APIBL.Model.ScoreGraphTracker)
  end
end

