# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.ScoreMetadata do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :pinnedContexts,
    :priority,
    :description,
    :linkService,
    :linkServiceIcon,
    :link
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :pinnedContexts => APIBL.Model.LeaderboardContexts.t | nil,
    :priority => integer() | nil,
    :description => String.t | nil,
    :linkService => String.t | nil,
    :linkServiceIcon => String.t | nil,
    :link => String.t | nil
  }

  alias APIBL.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:pinnedContexts, :struct, APIBL.Model.LeaderboardContexts)
  end
end

