# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.ScoreImprovement do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :timeset,
    :score,
    :accuracy,
    :pp,
    :bonusPp,
    :rank,
    :accRight,
    :accLeft,
    :averageRankedAccuracy,
    :totalPp,
    :totalRank,
    :badCuts,
    :missedNotes,
    :bombCuts,
    :wallsHit,
    :pauses
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :timeset => String.t | nil,
    :score => integer() | nil,
    :accuracy => float() | nil,
    :pp => float() | nil,
    :bonusPp => float() | nil,
    :rank => integer() | nil,
    :accRight => float() | nil,
    :accLeft => float() | nil,
    :averageRankedAccuracy => float() | nil,
    :totalPp => float() | nil,
    :totalRank => integer() | nil,
    :badCuts => integer() | nil,
    :missedNotes => integer() | nil,
    :bombCuts => integer() | nil,
    :wallsHit => integer() | nil,
    :pauses => integer() | nil
  }

  def decode(value) do
    value
  end
end

