# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.ScoreContextExtension do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :playerId,
    :player,
    :leaderboardId,
    :leaderboard,
    :weight,
    :rank,
    :baseScore,
    :modifiedScore,
    :accuracy,
    :pp,
    :passPP,
    :accPP,
    :techPP,
    :bonusPp,
    :modifiers,
    :timeset,
    :priority,
    :scoreId,
    :score,
    :qualification,
    :banned,
    :context,
    :scoreImprovement
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :playerId => String.t | nil,
    :player => APIBL.Model.Player.t | nil,
    :leaderboardId => String.t | nil,
    :leaderboard => APIBL.Model.Leaderboard.t | nil,
    :weight => float() | nil,
    :rank => integer() | nil,
    :baseScore => integer() | nil,
    :modifiedScore => integer() | nil,
    :accuracy => float() | nil,
    :pp => float() | nil,
    :passPP => float() | nil,
    :accPP => float() | nil,
    :techPP => float() | nil,
    :bonusPp => float() | nil,
    :modifiers => String.t | nil,
    :timeset => integer() | nil,
    :priority => integer() | nil,
    :scoreId => integer() | nil,
    :score => APIBL.Model.Score.t | nil,
    :qualification => boolean() | nil,
    :banned => boolean() | nil,
    :context => APIBL.Model.LeaderboardContexts.t | nil,
    :scoreImprovement => APIBL.Model.ScoreImprovement.t | nil
  }

  alias APIBL.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:player, :struct, APIBL.Model.Player)
     |> Deserializer.deserialize(:leaderboard, :struct, APIBL.Model.Leaderboard)
     |> Deserializer.deserialize(:score, :struct, APIBL.Model.Score)
     |> Deserializer.deserialize(:context, :struct, APIBL.Model.LeaderboardContexts)
     |> Deserializer.deserialize(:scoreImprovement, :struct, APIBL.Model.ScoreImprovement)
  end
end

