# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.SongSuggestSong do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :name,
    :hash,
    :difficulty,
    :mode,
    :stars
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :name => String.t | nil,
    :hash => String.t | nil,
    :difficulty => String.t | nil,
    :mode => String.t | nil,
    :stars => float() | nil
  }

  def decode(value) do
    value
  end
end

