# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.TopMapper do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :beatLeaderId,
    :beatSaverId,
    :name,
    :avatar,
    :minutesPlayed,
    :percentPlayers
  ]

  @type t :: %__MODULE__{
    :beatLeaderId => String.t | nil,
    :beatSaverId => String.t | nil,
    :name => String.t | nil,
    :avatar => String.t | nil,
    :minutesPlayed => float() | nil,
    :percentPlayers => float() | nil
  }

  def decode(value) do
    value
  end
end

