# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.TopMapCount do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :name,
    :mapper,
    :author,
    :cover,
    :previewLink,
    :count
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :name => String.t | nil,
    :mapper => String.t | nil,
    :author => String.t | nil,
    :cover => String.t | nil,
    :previewLink => String.t | nil,
    :count => integer() | nil
  }

  def decode(value) do
    value
  end
end

