# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.User do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :player,
    :clanRequest,
    :bannedClans,
    :playlists
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :player => APIBL.Model.Player.t | nil,
    :clanRequest => [APIBL.Model.Clan.t] | nil,
    :bannedClans => [APIBL.Model.Clan.t] | nil,
    :playlists => [APIBL.Model.Playlist.t] | nil
  }

  alias APIBL.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:player, :struct, APIBL.Model.Player)
     |> Deserializer.deserialize(:clanRequest, :list, APIBL.Model.Clan)
     |> Deserializer.deserialize(:bannedClans, :list, APIBL.Model.Clan)
     |> Deserializer.deserialize(:playlists, :list, APIBL.Model.Playlist)
  end
end

