# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.UserReturn do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :player,
    :clan,
    :ban,
    :clanRequest,
    :bannedClans,
    :playlists,
    :friends,
    :login,
    :migrated,
    :patreoned
  ]

  @type t :: %__MODULE__{
    :player => APIBL.Model.PlayerResponseFull.t | nil,
    :clan => APIBL.Model.ClanReturn.t | nil,
    :ban => APIBL.Model.BanReturn.t | nil,
    :clanRequest => [APIBL.Model.Clan.t] | nil,
    :bannedClans => [APIBL.Model.Clan.t] | nil,
    :playlists => [APIBL.Model.Playlist.t] | nil,
    :friends => [APIBL.Model.PlayerResponseFull.t] | nil,
    :login => String.t | nil,
    :migrated => boolean() | nil,
    :patreoned => boolean() | nil
  }

  alias APIBL.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:player, :struct, APIBL.Model.PlayerResponseFull)
     |> Deserializer.deserialize(:clan, :struct, APIBL.Model.ClanReturn)
     |> Deserializer.deserialize(:ban, :struct, APIBL.Model.BanReturn)
     |> Deserializer.deserialize(:clanRequest, :list, APIBL.Model.Clan)
     |> Deserializer.deserialize(:bannedClans, :list, APIBL.Model.Clan)
     |> Deserializer.deserialize(:playlists, :list, APIBL.Model.Playlist)
     |> Deserializer.deserialize(:friends, :list, APIBL.Model.PlayerResponseFull)
  end
end

