# NOTE: This file is auto generated by OpenAPI Generator 7.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule APIBL.Model.VoterFeedback do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :rtMember,
    :value
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :rtMember => String.t | nil,
    :value => float() | nil
  }

  def decode(value) do
    value
  end
end

